### ISSUE TITLE
Enable the scrollbar on website.

### ISSUE THREAD

**Issue by OmkarK45** [geist-org/geist-ui#444]
# Feature request 🚀
  - [x] It's just a suggestion

### Expected
Navigating the website without scrollbar is really difficult. Please enable scrollbar! My mouse scroller is not working properly so I have to be dependent on it to be able to use the website. Thanks

**Comment by harshcut** [comment]
The scrollbar is visible on **Firefox Developer Edition**.

**Comment by unix** [comment]
Hiding the scrollbars is for a consistent style, but user experience should be a priority, and does anyone want to create a PR for that?

**Comment by harshcut** [comment]
Do you want any custom styling?

**Comment by unix** [comment]
@harshcut 
Some time ago I thought about adding a scrollbar of [Twitch](https://www.twitch.tv/), the scrollbar component on the Twitch is really well done, it would be cool if we had one of those too. But I haven't figured out how to adapt it to some layouts, so maybe I can open another issue to talk about it.

**Comment by unix** [comment]
Redirect to #577
