### ISSUE TITLE
Add highlight on Tabs component

### ISSUE THREAD

**Issue by daviddossantos** [geist-org/geist-ui#653]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

Add highlight on Tabs component

  - Component 

https://user-images.githubusercontent.com/37313667/144487285-348358f2-1714-4c0f-bee7-4613cb610d47.mov

**Comment by nikhilgupta58** [comment]
I am picking this up...

**Comment by daviddossantos** [comment]
thanks @nikhilgupta58 ( ͡❛ ͜ʖ ͡❛)👌

**Comment by nikhilgupta58** [comment]
No issue @daviddossantos

**Comment by ofekashery** [comment]
@unix See https://emilkowal.ski/ui/tabs.

**Comment by unix** [comment]
Implemented in version 2.3.0.
