### ISSUE TITLE
Secondary button should be primary

### ISSUE THREAD

**Issue by ryan-eiv** [geist-org/geist-ui#691]
# Feature request 🚀

  - [x] It's just a suggestion

### Expected

I'm a big fan of Vercel's design and thank you for putting this together!

Based on how Vercel uses button themes, I think primary buttons should be black and secondary buttons should be white.

### Examples

![image](https://user-images.githubusercontent.com/95147135/151071296-8e7ebdda-d25d-4c55-b81c-b4ced0892cc2.png)

![image](https://user-images.githubusercontent.com/95147135/151071322-7c68eaec-2295-4afd-9089-90304cc71b76.png)

**Comment by unix** [comment]
This is a community component library (No relation to Vercel), Vercel's design is indeed a source of inspiration for us, but Geist will not remain exactly the same as Vercel.
