### ISSUE TITLE
Input styles not displaying on WebKit browser ( Safari )

### ISSUE THREAD

**Issue by ayushsharma82** [geist-org/geist-ui#717]
# Bug report 🐞

Input styles are not displayed correctly on WebKit based browsers. Something's wrong with the Geist UI's CSS.

Screenshot:
<img width="523" alt="Screenshot 2022-02-07 at 3 22 38 AM" src="https://user-images.githubusercontent.com/26592968/152702952-3dc3ff93-2dd2-42e8-b921-1034db0ac3ef.png">

## Version & Environment

  - Version of browser: latest
  - Version of `geist-ui/core`: latest

**Comment by ayushsharma82** [comment]
New findings: This is a problem only on docs page. Seems to work fine on local build.

**Comment by unix** [comment]
Thank you for your feedback, it was a style issue in the documentation site and has been fixed.
