### ISSUE TITLE
Prop 'width' could not be passed correctly

### ISSUE THREAD

**Issue by hothoney** [geist-org/geist-ui#731]
# Bug report 🐞

## Version & Environment

  - Version of browser: Chrome/98.0.4758.82
  - Version of `geist-ui/core`: 2.3.0

## Expected Behaviour

![image](https://user-images.githubusercontent.com/22422393/153700829-67ce9c2a-998f-4c99-abe9-c04608b59c0c.png)

## Actual results (or Errors)

![image](https://user-images.githubusercontent.com/22422393/153700842-c822b1a0-d46c-43d1-8e3d-bd1e93cf2cc7.png)

```
<InputPassword initialValue="123456abc" width="100%"/>
```

**Comment by unix** [comment]
version `v2.3.1` is out now.
