### ISSUE TITLE
`Button Dropdown` component contains an extra arrow in macOS Safari

### ISSUE THREAD

**Issue by samzhangjy** [geist-org/geist-ui#739]
# Bug report 🐞

## Version & Environment

  - Version of browser: Safari 15.2 (17612.3.6.1.6)
  - Version of `geist-ui/core`: I'm using `geist-ui/react` with version `2.2.0`. However, this issue also occurs in the docs.

## Expected Behaviour

The behavior I expect is a dropdown with only one single arrow.

## Actual results (or Errors)

I actually got two dropdown arrows within one dropdown button:

<img width="244" alt="image" src="https://user-images.githubusercontent.com/56634385/153740899-bb506986-2c79-4beb-973e-6b9f40052ee1.png">

## Other Information

I also tested this in macOS Edge and the behavior is normal.

**Comment by unix** [comment]
Thanks for the feedback, this issue was fixed in `v2.3.3`.
