### ISSUE TITLE
Figma Design Kit

### ISSUE THREAD

**Issue by bestony** [geist-org/geist-ui#744]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

  - a Figma Design Kit For Developer to design a geist-ui based system.

### Examples

   - Element UI Figma Kit：https://www.figma.com/community/file/1074978830391353170

**Comment by unix** [comment]
No additional design kit will be created and maintained in the short term, within the long-term plan, but a deadline cannot be promised.
