### ISSUE TITLE
Tabs don't work with JavaScript enabled

### ISSUE THREAD

**Issue by MaxLeiter** [geist-org/geist-ui#756]
# Bug report 🐞

Tabs require javascript to function.

## Version & Environment

  - N/A
  - ^2.3.5

## Expected Behaviour

Tabs should still show

## Actual results (or Errors)

Tabs do not show

**Comment by unix** [comment]
I don't understand what you mean, this is a React component lib, which of course requires js to be enabled in order to work. Or, are you meaning the Tabs need to be set `states` before they work?

Please provide more information or an online example (codes).

**Comment by MaxLeiter** [comment]
I expected the tabs to at least render with JS disabled, but looking at the code that would require a bit of work

**Comment by maritz** [comment]
@unix I think what he meant was server side renders don't render tab items.
