### ISSUE TITLE
[Bug]: The slider component is easy to trigger click events during the dragging process

### ISSUE THREAD

**Issue by nonzzz** [geist-org/geist-ui#774]
# Bug report 🐞

## Version & Environment

  - Chrome 100.
  - latest version of geist

## Expected Behaviour

From the docs we can see , when we  drag the dof. It's easy way to trigger click event. It's unreasonable.
I think it can be fixed :)

## Actual results (or Errors)

From source code. we can add a lock for `dragHandler`, and add unlock logic for `clickHandler`.

**Comment by deepfates** [comment]
Also running into this issue. Is there any news on this PR?

**Comment by nonzzz** [comment]
@deepfates I already fix it. Waiting for the owner to review. :)

**Comment by samuelmaker** [comment]
adding prop onClick={() => {}} on the slider fixed issue for me

**Comment by nonzzz** [comment]
> adding prop onClick={() => {}} on the slider fixed issue for me
Sadly,In my case. I need use `onClick` too. So the solution doesn't work for me

**Comment by samuelmaker** [comment]
@nonzzz Understood. Hope you get it resolved
