### ISSUE TITLE
Next.js installation guide is incorrect

### ISSUE THREAD

**Issue by nexxeln** [geist-org/geist-ui#775]
# About `docs`

This is a document site related issue.

### Languages

  - [x] English
  - [x] Chinese

### Description
In the [installation guide](https://geist-ui.dev/en-us/guide/installation), the Next.js example is importing the provider from `@geist-ui/react` and not `@geist-ui/core`

### Page Links (Optional)
https://geist-ui.dev/en-us/guide/installation

**Comment by unix** [comment]
thanks, merged.
