### ISSUE TITLE
关于导航菜单栏

### ISSUE THREAD

**Issue by 9AM751** [geist-org/geist-ui#791]
![image](https://user-images.githubusercontent.com/78640296/182018617-dd8b0caa-b6bf-4d59-a4b8-d4cf61fbd122.png)
我在文档中没有找到导航菜单栏这个组件，感觉这个导航菜单栏挺舒服的，请问这个会有吗QWQ

**Comment by unix** [comment]
这个属于文档开发的，你可以在 `/pages` 文件夹下面查看。
不会开源，因为这不属于组件，算是 Geist 组件的最佳实践吧。如果感觉不错，可以参考代码~
