### ISSUE TITLE
Change icon name to prevent duplicate import

### ISSUE THREAD

**Issue by satoshiman** [geist-org/geist-ui#801]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

  - Change Icons name from ```@geist-ui/icons``` difference from components import from ```@geist-ui/core``` to prevent duplicate import. For example, add suffix ```Icon``` to current Icon components.
  - Add ```Copy Icon name``` on icon docs section

### Examples

<img width="273" alt="image" src="https://user-images.githubusercontent.com/37683529/196716836-d94e0766-05da-40ca-8c07-91e3eb2f5992.png">

<img width="443" alt="image" src="https://user-images.githubusercontent.com/37683529/196720740-6c9f22fb-2339-4227-b6e8-dc92920aa656.png">

### Others (Optional)

Here is my case, I have to change the icon name to prevent duplicate import

**Comment by unix** [comment]
Yes, it is true that you need to use `as` to name. This doesn't seem to have a huge impact, and I use it the same way 🤣
